version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quanlythucpham-server
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: npm run start:prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 