services:
  - type: web
    name: quanlythucpham-backend
    env: node
    plan: free
    region: singapore
    buildCommand: cd Server && npm install && npm run build
    startCommand: cd Server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: NODE_ENV
        value: production 