services:
  - type: web
    name: quanlythucpham-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 16.20.0
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: "true" 